// <auto-generated />
using System;
using BaiKiemTraLan3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BaiKiemTraLan3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BaiKiemTraLan3.Models.Entitiesss.Cake", b =>
                {
                    b.Property<int>("MaBanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DaXoa")
                        .HasColumnType("bit");

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<string>("HanSuDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("MaTheLoai")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ThanhPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaBanh");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("Banhs");

                    b.HasData(
                        new
                        {
                            MaBanh = 1,
                            DaXoa = false,
                            GiaBan = 16000,
                            HanSuDung = "3 tháng",
                            MaTheLoai = 1,
                            NgaySanXuat = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBanh = "Bánh quy",
                            ThanhPhan = "Bột mỳ, trứng"
                        },
                        new
                        {
                            MaBanh = 2,
                            DaXoa = false,
                            GiaBan = 150000,
                            HanSuDung = "3 tháng",
                            MaTheLoai = 2,
                            NgaySanXuat = new DateTime(2020, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBanh = "Bánh sinh nhật",
                            ThanhPhan = "Bột mỳ, trứng"
                        },
                        new
                        {
                            MaBanh = 3,
                            DaXoa = false,
                            GiaBan = 16000,
                            HanSuDung = "3 tháng",
                            MaTheLoai = 3,
                            NgaySanXuat = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenBanh = "Bánh dừa bến tre",
                            ThanhPhan = "Bột gạo, trứng"
                        });
                });

            modelBuilder.Entity("BaiKiemTraLan3.Models.Entitiesss.Category", b =>
                {
                    b.Property<int>("MaTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("MaTheLoai");

                    b.ToTable("TheLoais");

                    b.HasData(
                        new
                        {
                            MaTheLoai = 1,
                            TenTheLoai = "Bánh ngọt"
                        },
                        new
                        {
                            MaTheLoai = 2,
                            TenTheLoai = "Bánh kem"
                        },
                        new
                        {
                            MaTheLoai = 3,
                            TenTheLoai = "Bánh dừa"
                        },
                        new
                        {
                            MaTheLoai = 4,
                            TenTheLoai = "Bánh mỳ"
                        },
                        new
                        {
                            MaTheLoai = 5,
                            TenTheLoai = "Bánh gato"
                        });
                });

            modelBuilder.Entity("BaiKiemTraLan3.Models.Entitiesss.Cake", b =>
                {
                    b.HasOne("BaiKiemTraLan3.Models.Entitiesss.Category", "TheLoai")
                        .WithMany("Banhs")
                        .HasForeignKey("MaTheLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
