// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WBDDemo.Models;

namespace WBDDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200819141116_SeedingEmployeeData")]
    partial class SeedingEmployeeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WBDDemo.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(18)")
                        .HasMaxLength(18);

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarPath = "~/images/chicharito.jfif",
                            Department = 3,
                            Email = "hatdaunho@gmail.com",
                            Fullname = "Chicharito"
                        },
                        new
                        {
                            Id = 2,
                            AvatarPath = "~/images/no_image.jfif",
                            Department = 2,
                            Email = "hoangtutocvang@gmail.com",
                            Fullname = "PaulScholes"
                        },
                        new
                        {
                            Id = 3,
                            AvatarPath = "~/images/park.jfif",
                            Department = 2,
                            Email = "hatdaunho@gmail.com",
                            Fullname = "Park Ji Sung"
                        },
                        new
                        {
                            Id = 4,
                            AvatarPath = "~/images/dasilva.jfif",
                            Department = 1,
                            Email = "hoangtutocvang@gmail.com",
                            Fullname = "Rafael Da Silva"
                        },
                        new
                        {
                            Id = 5,
                            AvatarPath = "~/images/rio.jfif",
                            Department = 1,
                            Email = "hatdaunho@gmail.com",
                            Fullname = "Ferdinand"
                        },
                        new
                        {
                            Id = 6,
                            AvatarPath = "~/images/carrick.jfif",
                            Department = 2,
                            Email = "hoangtutocvang@gmail.com",
                            Fullname = "Carrick"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
